---
- name: Clone powerline font repository
  git:
    repo: "https://github.com/powerline/fonts"
    dest: /tmp/checkout

- name: Launch install of fonts
  command: "./install.sh"
  args:
    chdir: /tmp/checkout/fonts

- name: delete repository
  file:
    path: /tmp/checkout
    state: absent

- name: Install powerline-shell with pip
  pip:
    name: powerline-shell
    extra_args: --user

- name: update bashrc
  blockinfile:
    path: "{{ ansible_env['HOME'] }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK powerline-shell"
    block: |
      function _update_ps1() {
        PS1=$(powerline-shell $?)
      }
      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

- name: create configuration folder
  file:
    path: "{{ ansible_env['HOME'] }}/.config/powerline-shell/"
    state: directory

- name: copy configuration
  copy:
    src: powerline-shell.json
    dest: "{{ ansible_env['HOME'] }}/.config/powerline-shell/config.json"
